# Generated by Django 6.0.1 on 2026-01-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microapp',
            name='icon_name',
            field=models.CharField(default='image-application', help_text='Material Design Icon name', max_length=50),
        ),
    ]
