# ใช้ Python รุ่นเล็ก (Slim) เพื่อประหยัดพื้นที่
FROM python:3.12-slim

# ตั้งค่าไม่ให้ Python สร้างไฟล์ .pyc และให้แสดงผล log ทันที
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# สร้างโฟลเดอร์ทำงานข้างใน Container
WORKDIR /app

# ติดตั้ง Dependencies สำหรับ Postgres (สำคัญมาก!)
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# ก๊อปปี้ไฟล์รายการ library เข้าไป
COPY requirements.txt .

# ติดตั้ง library
RUN pip install --no-cache-dir -r requirements.txt

# ก๊อปปี้โค้ดทั้งหมดเข้าไป
COPY . .

# เปิดประตู Port 8000
EXPOSE 8000

# คำสั่งรัน Server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]